In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])
print(a1)

[1 2 3]


In [4]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a1[1]

2

In [7]:
a2[1,2] #segunda superficie el tercer elemento, osea el 6

6

In [8]:
av=np.empty([4,3])
av

array([[4.63999976e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.10343781e-312, 1.92015270e-052],
       [2.49275842e+180, 4.51481735e-037, 1.61501231e+160],
       [3.26939160e-032, 3.53865297e-057, 6.17439055e-062]])

In [9]:
az=np.zeros([3,5])
az

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
ao=np.ones([3,8])
ao

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
af=np.full([3,8], 5)
af

array([[5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [13]:
ai=np.identity(5)
ai

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [16]:
ar=np.arange(1,10,2)
ar

array([1, 3, 5, 7, 9])

In [17]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
          axis=0)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples

In [18]:
al=np.linspace(1,50,10)
al

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
aran=np.random.random([2,3])
aran

array([[0.46959864, 0.98510057, 0.05534318],
       [0.95356644, 0.31122385, 0.61500671]])

In [22]:
aran.ndim

2

In [23]:
aran.shape

(2, 3)

In [24]:
aran.size

6

In [25]:
aran.dtype

dtype('float64')

In [27]:
at=np.array(['hola','mundo'])
at.dtype
             

dtype('<U5')

In [28]:
al

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [29]:
np.info(al.astype)

a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

Copy of the array, cast to a specified type.

Parameters
----------
dtype : str or dtype
    Typecode or data-type to which the array is cast.
order : {'C', 'F', 'A', 'K'}, optional
    Controls the memory layout order of the result.
    'C' means C order, 'F' means Fortran order, 'A'
    means 'F' order if all the arrays are Fortran contiguous,
    'C' order otherwise, and 'K' means as close to the
    order the array elements appear in memory as possible.
    Default is 'K'.
casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'unsafe'
    for backwards compatibility.

      * 'no' means the data types should not be cast at all.
      * 'equiv' means only byte-order changes are allowed.
      * 'safe' means only casts which can preserve values are allowed.
      * 'same_kind' means only safe casts or casts within a kind,
        like float64

In [31]:
al.astype('i')#tranfor en enteros los números(integer)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50], dtype=int32)

In [32]:
np.sort(al)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [33]:
aran

array([[0.46959864, 0.98510057, 0.05534318],
       [0.95356644, 0.31122385, 0.61500671]])

In [34]:
np.sort(aran)

array([[0.05534318, 0.46959864, 0.98510057],
       [0.31122385, 0.61500671, 0.95356644]])

In [35]:
np.sort(aran,1)

array([[0.05534318, 0.46959864, 0.98510057],
       [0.31122385, 0.61500671, 0.95356644]])

In [43]:
arr=np.array([2,4,5,0,6,1,5,4,1,-3])

In [44]:
np.min(arr)

-3

In [45]:
np.max(arr)

6

In [46]:
np.median(arr)

3.0

In [47]:
np.unique(arr)

array([-3,  0,  1,  2,  4,  5,  6])

In [48]:
np.prod(arr)

0

In [49]:
for x in arr:
    print(x)

2
4
5
0
6
1
5
4
1
-3


In [50]:
for i in range(len(arr)):
    print(i,arr[i])

0 2
1 4
2 5
3 0
4 6
5 1
6 5
7 4
8 1
9 -3


In [51]:
for x in aran:
    for y in x:
        print(y)

0.4695986428540171
0.9851005700328095
0.05534317525986032
0.9535664418169291
0.311223853163614
0.6150067120153639
