In [2]:
#Crea arrays de 1, 2 y 3 dimensiones. Las longitudes deben ser las siguientes, respectivamente: 6, 3 x 2 y 2 x 3 x 4

a1 = np.random.rand(6)
a2 = np.random.rand(3, 2)
a3 = np.random.rand(2, 3, 4)
print(a1)
print(a2)
print(a3)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [9]:
#Crea arrays de 1, 2 y 3 dimensiones. Las longitudes deben ser las siguientes, respectivamente: 6, 3 x 2 y 2 x 3 x 4
a1 = np.random.rand(6)
a2 = np.random.rand(3, 2)
a3 = np.random.rand(2, 3, 4)
print("array1D:",a1)
print("array2D:",a2)
print("array3D:",a3)

array1D: [0.40923927 0.03836956 0.52907715 0.92630311 0.85266859 0.01792548]
array2D: [[0.19459235 0.28226144]
 [0.22034022 0.54558811]
 [0.57457558 0.00281926]]
array3D: [[[0.95751387 0.99150024 0.90201326 0.27905075]
  [0.17477269 0.28232692 0.17940622 0.59948503]
  [0.66864044 0.98294925 0.16997717 0.76462414]]

 [[0.67081001 0.47981695 0.44341223 0.36937004]
  [0.52455746 0.34975275 0.61882735 0.63381486]
  [0.8900095  0.20793026 0.87744756 0.48205556]]]


In [6]:
def crear_arrays():
    # Array de 1 dimensión
    array_1d = np.random.rand(6)
    
    # Array de 2 dimensiones
    array_2d = np.random.rand(3, 2)
    
    # Array de 3 dimensiones
    array_3d = np.random.rand(2, 3, 4)
    
    return array_1d, array_2d, array_3d

array_1d, array_2d, array_3d = crear_arrays()

print("Array de 1 dimensión:\n", array_1d)
print("Array de 2 dimensiones:\n", array_2d)
print("Array de 3 dimensiones:\n", array_3d)

Array de 1 dimensión:
 [0.59686835 0.73284931 0.66807472 0.80188042 0.82963945 0.32030231]
Array de 2 dimensiones:
 [[0.27962458 0.7535748 ]
 [0.1566797  0.15065834]
 [0.3426839  0.19894625]]
Array de 3 dimensiones:
 [[[0.0152451  0.78452765 0.68380466 0.42659019]
  [0.84076533 0.65212088 0.04898772 0.96289934]
  [0.64844453 0.59093093 0.21307831 0.35239612]]

 [[0.65974787 0.59656969 0.74087467 0.39754274]
  [0.5570179  0.96844073 0.31899487 0.32689106]
  [0.94330151 0.95593138 0.28971401 0.36907024]]]


In [17]:
#Crea una función que te haga un resumen estadístico básico de un array (cuartiles, mediana, media, varianza, etc) si tiene una dimensión.
#  Si tiene más de una, muestra un mensaje de alerta.



def resumen_estadistico(array):
    if array.ndim == 1:
        resumen = {
            'Media': np.mean(array),
            'Mediana': np.median(array),
            'Varianza': np.var(array),
            'Desviación estándar': np.std(array),
            'Cuartil 1': np.percentile(array, 25),
            'Cuartil 2 (Mediana)': np.percentile(array, 50),
            'Cuartil 3': np.percentile(array, 75)
        }
        return resumen
    else:
        return "El array tiene más de una dimensión. No se puede realizar el resumen estadístico."

# Ejemplo de uso
array_1d = np.random.rand(6)
array_2d = np.random.rand(3, 2)

print("Resumen estadístico del array de 1 dimensión:\n", resumen_estadistico(array_1d))
print("Intento de resumen estadístico del array de 2 dimensiones:\n", resumen_estadistico(array_2d))

Resumen estadístico del array de 1 dimensión:
 {'Media': 0.39008107833788125, 'Mediana': 0.4672941425042094, 'Varianza': 0.04156933228022098, 'Desviación estándar': 0.20388558624930056, 'Cuartil 1': 0.23416085654722568, 'Cuartil 2 (Mediana)': 0.4672941425042094, 'Cuartil 3': 0.5663821721356981}
Intento de resumen estadístico del array de 2 dimensiones:
 El array tiene más de una dimensión. No se puede realizar el resumen estadístico.


In [18]:
#Ejercicio 3.
#Crea un array de 3 dimensiones parecido al que te doy a continuación, y sin ejecutar las instrucciones siguientes, 
#intenta razonar qué números devolverán (si funcionan, claro)
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [4]:
arr[-1,-1,-1]

NameError: name 'arr' is not defined

In [6]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15],[16, 17, 18]], [[19, 20, 21],[22, 23, 24]] ])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [7]:
arr[-1,-1,-1]

24

In [9]:
arr[3,1,2]#es como arr[-1,-1,-1]

24

In [13]:
a1=np.ones([5,5])
print(a1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
az=np.zeros([3,3])
print(az)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
a1[1:4,1:4]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
a1[1:4,1:4]=az
print(a1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
def gen_cuadrado_1_0(n):
    a1=np.ones([n,n])
    a1[1:n-1,1:n-1]=0
    return a1
print(gen_cuadrado_1_0(a1)) #revisar

    

TypeError: only integer scalar arrays can be converted to a scalar index