In [6]:

#Ejercicio 1:
#Crea una matriz 1D con valores que van del 0 al 9.
import numpy as np
arr1= np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [20]:
#Ejercicio 2:
#Convierte una matriz 1D en una matriz 2D con 2 filas
arr1=np.array([1,2,3,4,5,6])
arr2=arr1.reshape(2,3)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Ejercicio 3:
#Multiplica una matriz de 5x3 por una matriz de 3x2.